#Jekyll configuration
title: EDRMedeso Productivity Tools for Ansys
logo: /images/EDR-Medeso_logo.png
description: Apps (Extensions) for Ansys created by EDRMedeso.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
